ALTER TABLE analytics.learning_daily 
ADD COLUMN IF NOT EXISTS learning_starts INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS completion_rate NUMERIC(5, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS top_courses JSONB NULL;
