import type { Metadata } from "next";
import Link from "next/link";

import { EmptyState, ErrorState, PageHero } from "@/components/public-content";
import { listLearningPaths } from "@/lib/learning-paths";

export const metadata:Metadata={title:"Jalur Belajar",description:"Ikuti jalur belajar bertahap di Teman Belajar.",alternates:{canonical:"/learning-paths"}};
function href(query:string,page:number){const params=new URLSearchParams();if(query)params.set("q",query);if(page>1)params.set("page",String(page));return `/learning-paths${params.size?`?${params}`:""}`}
export default async function LearningPathsPage({searchParams}:{searchParams:Promise<{q?:string;page?:string}>}){const raw=await searchParams;const query=(raw.q||"").trim().slice(0,100);const page=Math.max(1,Number.parseInt(raw.page||"1",10)||1);const result=await listLearningPaths(query,page);return <div><PageHero eyebrow="Jalur Belajar" title="Langkah terarah menuju kompetensi berikutnya" description="Gabungkan course Moodle, pengetahuan, pembelajaran singkat, dan sesi langsung dalam urutan yang dapat dipahami."/><section className="portal-container py-10 sm:py-14"><form role="search" className="portal-card mb-8 flex flex-col gap-3 p-4 sm:flex-row" action="/learning-paths"><label htmlFor="path-search" className="sr-only">Cari Jalur Belajar</label><input id="path-search" name="q" type="search" maxLength={100} defaultValue={query} placeholder="Cari jalur berdasarkan tujuan belajar" className="portal-search-input min-h-11 flex-1"/><button className="portal-button-primary min-h-11">Cari jalur</button>{query?<Link href="/learning-paths" className="portal-button-secondary min-h-11">Hapus filter</Link>:null}</form>{result.error?<ErrorState title="Jalur Belajar belum dapat dimuat"/>:result.data.length===0?<EmptyState title={query?"Jalur tidak ditemukan":"Belum ada jalur terbit"} description="Jalur yang telah ditinjau dan diterbitkan akan tampil di sini."/>:<><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{result.data.map(path=><article key={path.id} className="portal-card portal-course-card p-6"><div className="flex flex-wrap gap-2"><span className="portal-badge">Versi {path.version.number}</span><span className="portal-badge">{path.version.items.length} langkah</span></div><h2 className="mt-5 text-xl font-black text-slate-900"><Link href={`/learning-paths/${path.slug}`} className="hover:text-teal-700">{path.version.title}</Link></h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{path.version.summary}</p><div className="mt-auto border-t border-slate-100 pt-5"><Link href={`/learning-paths/${path.slug}`} className="font-extrabold text-teal-700">Lihat jalur →</Link></div></article>)}</div>{result.pagination.total_pages>1?<nav aria-label="Paginasi Jalur Belajar" className="mt-10 flex items-center justify-between border-t border-slate-200 pt-6"><Link aria-disabled={page<=1} tabIndex={page<=1?-1:undefined} href={href(query,Math.max(1,page-1))} className={`portal-button-secondary ${page<=1?"pointer-events-none opacity-40":""}`}>← Sebelumnya</Link><p className="text-sm font-semibold text-slate-500">Halaman {page} dari {result.pagination.total_pages}</p><Link aria-disabled={page>=result.pagination.total_pages} tabIndex={page>=result.pagination.total_pages?-1:undefined} href={href(query,Math.min(result.pagination.total_pages,page+1))} className={`portal-button-secondary ${page>=result.pagination.total_pages?"pointer-events-none opacity-40":""}`}>Berikutnya →</Link></nav>:null}</>}</section></div>}
