"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createMicrolearningAction, getMicrolearningWorkspaceAction, transitionMicrolearningAction, updateMicrolearningAction, type MicrolearningInput, type MicrolearningItem, type MicrolearningStatus } from "@/app/actions/microlearning";
import { AdminIcon } from "@/components/admin-icon";
import MediaPicker from "@/components/media/MediaPicker";

type Draft = Omit<MicrolearningInput,"expected_version">;
const emptyDraft:Draft={slug:"",title:"",summary:"",body:"",format:"quick",duration_minutes:5,video_url:"",featured_media_id:"",related_ids:[],seo_title:"",seo_description:"",indexable:true};
const labels:Record<MicrolearningStatus,string>={draft:"Draf",in_review:"Peninjauan",approved:"Disetujui",published:"Terbit",archived:"Diarsipkan"};
const formatLabels={quick:"Quick learning",article:"Artikel",video:"Video"};
const slugify=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,160);
const draftFrom=(x:MicrolearningItem):Draft=>({slug:x.slug,title:x.title,summary:x.summary,body:x.body,format:x.format,duration_minutes:x.duration_minutes,video_url:x.video_url||"",featured_media_id:x.featured_media_id||"",related_ids:x.related.map(item=>item.id),seo_title:x.seo_title||"",seo_description:x.seo_description||"",indexable:x.indexable});

export default function MicrolearningAdminPage(){
  const[items,setItems]=useState<MicrolearningItem[]>([]);const[roles,setRoles]=useState<string[]>([]);const[selected,setSelected]=useState<MicrolearningItem|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[creating,setCreating]=useState(false);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[query,setQuery]=useState("");const[status,setStatus]=useState("all");const[format,setFormat]=useState("");
  const canWrite=roles.some(role=>["Portal Administrator","Content Editor"].includes(role));const canReview=roles.some(role=>["Portal Administrator","Reviewer"].includes(role));
  const load=useCallback(async()=>{const result=await getMicrolearningWorkspaceAction({q:query,status,format});setLoading(false);setRoles(result.roles);if(!result.success){setError(result.error);setItems([]);return}setItems(result.items);setError("")},[query,status,format]);
  useEffect(()=>{let active=true;void getMicrolearningWorkspaceAction({q:query,status,format}).then(result=>{if(!active)return;setLoading(false);setRoles(result.roles);if(!result.success){setError(result.error);setItems([]);return}setItems(result.items);setError("")});return()=>{active=false}},[query,status,format]);
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}));const choose=(item:MicrolearningItem)=>{setSelected(item);setDraft(draftFrom(item));setCreating(false);setError("");setNotice("")};const startCreate=()=>{setSelected(null);setDraft(emptyDraft);setCreating(true);setError("");setNotice("")};const editable=canWrite&&(!selected||selected.status==="draft");
  const relatedOptions=useMemo(()=>items.filter(item=>item.id!==selected?.id&&item.status!=="archived"),[items,selected]);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");const input:MicrolearningInput={...draft,video_url:draft.format==="video"?draft.video_url:"",expected_version:selected?.version};const result=selected?await updateMicrolearningAction(selected.id,input):await createMicrolearningAction(input);setBusy(false);if(!result.success){setError(result.error);return}setSelected(result.data);setDraft(draftFrom(result.data));setCreating(false);setNotice(selected?"Materi berhasil diperbarui.":"Draf materi berhasil dibuat.");await load()}
  async function transition(next:MicrolearningStatus){if(!selected)return;setBusy(true);const result=await transitionMicrolearningAction(selected.id,next);setBusy(false);if(!result.success){setError(result.error);return}setSelected(result.data);setDraft(draftFrom(result.data));setNotice(`Materi dipindahkan ke ${labels[next]}.`);await load()}
  const actions:Array<{status:MicrolearningStatus;label:string}>=[];if(selected?.status==="draft"&&canWrite)actions.push({status:"in_review",label:"Ajukan peninjauan"});if(selected?.status==="in_review"&&canReview)actions.push({status:"draft",label:"Kembalikan ke draf"},{status:"approved",label:"Setujui"});if(selected?.status==="approved"&&canReview)actions.push({status:"draft",label:"Kembalikan ke draf"},{status:"published",label:"Terbitkan"});if(selected?.status==="published"&&(canWrite||canReview))actions.push({status:"archived",label:"Arsipkan"});
  return <div className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">TASK-014 · Editorial Portal</p><h1 className="admin-page-title">Pembelajaran Singkat</h1><p className="admin-page-copy">Kelola materi 3–15 menit. Progresnya ringan dan tidak menjadi completion Moodle.</p></div>{canWrite?<button type="button" className="admin-button" onClick={startCreate}><AdminIcon name="file" className="h-4 w-4"/>Materi baru</button>:null}</header>
  {error?<div role="alert" className="mb-5 rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm font-bold text-rose-800">{error}</div>:null}{notice?<div role="status" className="mb-5 rounded-xl border border-sky-300 bg-sky-50 p-4 text-sm font-bold text-sky-900">{notice}</div>:null}
  <div className="grid gap-6 xl:grid-cols-[23rem_minmax(0,1fr)]"><aside className="admin-card self-start"><div className="admin-card-header"><h2 className="font-black">Daftar materi</h2></div><div className="admin-card-body"><div className="grid gap-3"><label htmlFor="micro-search" className="admin-label">Cari</label><input id="micro-search" className="admin-input" value={query} maxLength={100} onChange={event=>setQuery(event.target.value)}/><div className="grid grid-cols-2 gap-3"><select aria-label="Status" className="admin-input" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Semua status</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Format" className="admin-input" value={format} onChange={event=>setFormat(event.target.value)}><option value="">Semua format</option>{Object.entries(formatLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></div><div className="mt-5 grid gap-2">{loading?<p role="status" className="text-sm text-slate-500">Memuat materi…</p>:items.length===0?<p className="admin-empty">Belum ada materi pada filter ini.</p>:items.map(item=><button type="button" key={item.id} onClick={()=>choose(item)} className={`admin-list-item text-left ${selected?.id===item.id?"is-active":""}`}><span><strong className="block text-sm">{item.title}</strong><span className="mt-1 block text-xs opacity-70">{formatLabels[item.format]} · {item.duration_minutes} menit</span></span><span className="admin-status admin-status-neutral">{labels[item.status]}</span></button>)}</div></div></aside>
  <main>{!selected&&!creating?<div className="admin-empty rounded-2xl border"><AdminIcon name="knowledge" className="mx-auto h-6 w-6"/><h2 className="mt-4 text-xl font-black">Pilih materi untuk ditinjau</h2></div>:<form onSubmit={submit} className="admin-form-card"><div className="admin-form-header"><div><p className="admin-kicker">{selected?"Detail materi":"Materi baru"}</p><h2 className="text-xl font-black">{selected?.title||"Susun microlearning"}</h2></div>{selected?<span className="admin-status admin-status-neutral">{labels[selected.status]}</span>:null}</div><fieldset disabled={!editable||busy} className="admin-form-body"><div className="grid gap-5 md:grid-cols-2"><div><label htmlFor="micro-title" className="admin-label">Judul *</label><input id="micro-title" required minLength={3} maxLength={200} className="admin-input" value={draft.title} onChange={event=>{set("title",event.target.value);if(!selected)set("slug",slugify(event.target.value))}}/></div><div><label htmlFor="micro-slug" className="admin-label">Slug *</label><input id="micro-slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={160} className="admin-input" value={draft.slug} onChange={event=>set("slug",event.target.value)}/></div></div><div><label htmlFor="micro-summary" className="admin-label">Ringkasan *</label><textarea id="micro-summary" required minLength={10} maxLength={500} rows={3} className="admin-input" value={draft.summary} onChange={event=>set("summary",event.target.value)}/></div><div><label htmlFor="micro-body" className="admin-label">Isi editorial *</label><textarea id="micro-body" required minLength={20} maxLength={20000} rows={10} className="admin-input" value={draft.body} onChange={event=>set("body",event.target.value)}/></div><div className="grid gap-5 md:grid-cols-2"><div><label htmlFor="micro-format" className="admin-label">Format *</label><select id="micro-format" className="admin-input" value={draft.format} onChange={event=>set("format",event.target.value as Draft["format"])}>{Object.entries(formatLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div><label htmlFor="micro-duration" className="admin-label">Durasi (menit) *</label><input id="micro-duration" type="number" min={3} max={15} required className="admin-input" value={draft.duration_minutes} onChange={event=>set("duration_minutes",Number(event.target.value))}/></div></div>{draft.format==="video"?<div><label htmlFor="micro-video" className="admin-label">URL video HTTPS *</label><input id="micro-video" type="url" required pattern="https://.*" maxLength={2048} className="admin-input" value={draft.video_url} onChange={event=>set("video_url",event.target.value)}/><p className="mt-2 text-xs text-slate-500">Video memakai sumber HTTPS terkurasi. Policy upload Media tetap gambar/PDF.</p></div>:null}
  <section className="rounded-xl border border-slate-200 p-4"><h3 className="font-black">Cover dari Pustaka Media</h3><p className="mt-1 text-xs text-slate-500">Hanya aset gambar aktif dari policy endpoint.</p><div className="mt-3 flex flex-wrap items-center gap-3"><MediaPicker imageOnly buttonLabel="Pilih cover" onSelect={media=>set("featured_media_id",media.id)}/>{draft.featured_media_id?<><span className="text-xs font-bold text-slate-600">Aset {draft.featured_media_id.slice(0,8)}…</span><button type="button" className="admin-button-secondary" onClick={()=>set("featured_media_id","")}>Hapus cover</button></>:null}</div></section>
  <section><h3 className="font-black">Materi terkait</h3><p className="mt-1 text-xs text-slate-500">Maksimal delapan materi; hanya materi terbit tampil di Portal.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{relatedOptions.map(item=><label key={item.id} className="admin-taxonomy-row"><input type="checkbox" checked={draft.related_ids.includes(item.id)} disabled={!draft.related_ids.includes(item.id)&&draft.related_ids.length>=8} onChange={event=>set("related_ids",event.target.checked?[...draft.related_ids,item.id]:draft.related_ids.filter(id=>id!==item.id))}/><span><strong className="block text-sm">{item.title}</strong><span className="text-xs text-slate-500">{labels[item.status]}</span></span></label>)}</div></section>
  <section className="rounded-xl bg-slate-50 p-4"><h3 className="font-black">SEO publik</h3><div className="mt-4 grid gap-4"><div><label htmlFor="micro-seo-title" className="admin-label">Judul SEO</label><input id="micro-seo-title" maxLength={70} className="admin-input" value={draft.seo_title} onChange={event=>set("seo_title",event.target.value)}/></div><div><label htmlFor="micro-seo-description" className="admin-label">Deskripsi SEO</label><textarea id="micro-seo-description" maxLength={160} rows={3} className="admin-input" value={draft.seo_description} onChange={event=>set("seo_description",event.target.value)}/></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={draft.indexable} onChange={event=>set("indexable",event.target.checked)}/>Izinkan indeks pencarian dan mesin pencari</label></div></section></fieldset><div className="admin-form-actions">{editable?<button className="admin-button" disabled={busy}>{busy?"Menyimpan…":"Simpan draf"}</button>:<p className="text-sm text-slate-500">Hanya draf yang dapat diedit.</p>}{actions.map(action=><button key={action.status} type="button" className="admin-button-secondary" disabled={busy} onClick={()=>transition(action.status)}>{action.label}</button>)}</div></form>}</main></div></div>;
}
