import type { Metadata } from "next";
/* eslint-disable @next/next/no-img-element -- public media route is access-controlled and not compatible with the image optimizer */
import Link from "next/link";
import { notFound } from "next/navigation";

import { MicrolearningState } from "@/components/microlearning/microlearning-state";
import { StructuredData } from "@/components/structured-data";
import { absolutePublicUrl } from "@/lib/discovery/types";
import { getMicrolearning, getMicrolearningLearnerState } from "@/lib/microlearning";

const labels = { article: "Artikel", video: "Video", quick: "Quick learning" } as const;
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = await getMicrolearning(slug); if (!item) return { title: "Materi tidak ditemukan" }; return { title: item.seo_title || item.title, description: item.seo_description || item.summary, alternates: { canonical: `/microlearning/${item.slug}` }, robots: item.indexable ? { index: true, follow: true } : { index: false, follow: true }, openGraph: { type: "article", title: item.seo_title || item.title, description: item.seo_description || item.summary, images: item.featured_media_id ? [{ url: `/media/${item.featured_media_id}`, alt: item.title }] : undefined } }; }

export default async function MicrolearningDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const item = await getMicrolearning(slug); if (!item) notFound(); const learner = await getMicrolearningLearnerState(item.id); const canonical = absolutePublicUrl(`/microlearning/${item.slug}`);
  return <div><StructuredData value={{ "@context": "https://schema.org", "@type": "LearningResource", name: item.title, description: item.summary, url: canonical, timeRequired: `PT${item.duration_minutes}M`, learningResourceType: labels[item.format], isAccessibleForFree: true }} />
    <section className="portal-course-hero border-b border-slate-200"><div className="portal-course-hero-shape portal-course-hero-shape-one"/><div className="portal-course-hero-shape portal-course-hero-shape-two"/><div className="portal-container relative z-10 grid gap-10 py-14 lg:grid-cols-[1fr_22rem] lg:items-center lg:py-20"><div><Link href="/microlearning" className="portal-course-hero-label">← Pembelajaran Singkat</Link><div className="mt-5 flex gap-2"><span className="portal-badge">{labels[item.format]}</span><span className="portal-badge">{item.duration_minutes} menit</span></div><h1 className="portal-course-hero-title">{item.title}</h1><p className="portal-course-hero-copy">{item.summary}</p><div className="portal-course-hero-trust"><span>Editorial Portal</span><span>Bukan completion Moodle</span><span>Materi terkurasi</span></div></div><aside className="portal-card overflow-hidden">{item.featured_media_id ? <img src={`/media/${item.featured_media_id}`} alt="" className="aspect-video w-full object-cover" /> : <div className="flex aspect-video items-center justify-center bg-gradient-to-br from-teal-700 to-sky-700 text-5xl font-black text-white">{item.duration_minutes}</div>}<div className="p-5 text-sm leading-6 text-slate-600">Selesaikan sesuai ritme Anda dan simpan posisi untuk dilanjutkan nanti.</div></aside></div></section>
    <section className="portal-container grid gap-8 py-12 lg:grid-cols-[minmax(0,1fr)_22rem]"><article id="microlearning-content" tabIndex={-1}><p className="portal-eyebrow">Materi pembelajaran</p>{item.format === "video" && item.video_url ? <video controls preload="metadata" src={item.video_url} className="mt-5 aspect-video w-full rounded-2xl bg-slate-950" aria-label={`Video ${item.title}`}>Browser Anda tidak mendukung pemutar video. <a href={item.video_url}>Buka video</a>.</video> : null}<div className="mt-7 whitespace-pre-line text-base leading-8 text-slate-700">{item.body}</div></article><aside className="self-start lg:sticky lg:top-24">{learner.authenticated ? <MicrolearningState itemId={item.id} format={item.format} durationMinutes={item.duration_minutes} initialProgress={learner.progress} initialBookmarked={learner.bookmarked} /> : <div className="portal-card p-5"><h2 className="font-black text-slate-900">Simpan posisi belajar</h2><p className="mt-2 text-sm leading-6 text-slate-600">Masuk untuk bookmark dan melanjutkan materi dari posisi terakhir.</p><Link href={`/api/auth/signin?callbackUrl=${encodeURIComponent(`/microlearning/${slug}`)}`} className="portal-button-primary mt-5 w-full">Masuk</Link></div>}</aside></section>
    {item.related.length ? <section className="portal-container pb-14" aria-labelledby="related-microlearning"><p className="portal-eyebrow">Lanjutkan eksplorasi</p><h2 id="related-microlearning" className="mt-2 text-2xl font-black text-slate-900">Materi terkait</h2><div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{item.related.map((related) => <article key={related.id} className="portal-card p-5"><div className="flex gap-2"><span className="portal-badge">{labels[related.format]}</span><span className="portal-badge">{related.duration_minutes} menit</span></div><h3 className="mt-4 font-black text-slate-900"><Link href={`/microlearning/${related.slug}`} className="hover:text-teal-700">{related.title}</Link></h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">{related.summary}</p></article>)}</div></section> : null}
  </div>;
}
