"use client";

/* eslint-disable @next/next/no-img-element -- Preview URLs are authenticated BFF resources discovered at runtime. */

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";

import { AdminIcon } from "@/components/admin-icon";

type MediaAsset = { id: string; original_filename?: string | null; detected_mime_type: string; size_bytes: number; title?: string | null; alt_text?: string | null; caption?: string | null; status: string; created_at: string };

export default function MediaDetailPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const [asset, setAsset] = useState<MediaAsset | null>(null);
  const [title, setTitle] = useState(""); const [altText, setAltText] = useState(""); const [caption, setCaption] = useState("");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");

  useEffect(() => { const controller = new AbortController(); const load = async () => { try { const response = await fetch(`/api/bff/media/${id}`, { signal: controller.signal }); if (!response.ok) throw new Error("Detail media belum dapat dimuat"); const payload = await response.json(); const data = payload.data || payload; setAsset(data); setTitle(data.title || ""); setAltText(data.alt_text || ""); setCaption(data.caption || ""); } catch (caught) { if (!controller.signal.aborted) setError(caught instanceof Error ? caught.message : "Detail media belum dapat dimuat"); } finally { if (!controller.signal.aborted) setLoading(false); } }; void load(); return () => controller.abort(); }, [id]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`/api/bff/media/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title || null, alt_text: altText || null, caption: caption || null }) }); if (!response.ok) throw new Error("Metadata media belum dapat disimpan"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Metadata media belum dapat disimpan"); } finally { setSaving(false); } };
  const archive = async () => { if (!window.confirm("Arsipkan media ini? Konten yang masih menggunakannya harus ditinjau terlebih dahulu.")) return; setSaving(true); setError(""); try { const response = await fetch(`/api/bff/media/${id}/archive`, { method: "POST" }); if (!response.ok) throw new Error("Media belum dapat diarsipkan"); router.push("/dashboard/media"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Media belum dapat diarsipkan"); setSaving(false); } };

  if (loading) return <div className="admin-card animate-pulse p-8"><div className="h-7 w-52 rounded bg-slate-100" /><div className="mt-5 h-72 rounded-xl bg-slate-100" /></div>;
  if (!asset) return <div className="admin-card mx-auto max-w-xl p-8 text-center" role="alert"><h1 className="text-xl font-black text-slate-900">Media tidak tersedia</h1><p className="mt-3 text-sm text-slate-500">{error}</p><Link href="/dashboard/media" className="admin-button mt-6">Kembali</Link></div>;

  return <div className="admin-page max-w-6xl"><div className="admin-page-header"><div><Link href="/dashboard/media" className="text-sm font-bold text-sky-700">← Kembali ke Media Library</Link><p className="admin-kicker mt-5">Detail aset</p><h1 className="admin-page-title">Kelola media</h1><p className="admin-page-copy">Lengkapi metadata aksesibilitas sebelum digunakan pada konten.</p></div><span className={`admin-status ${asset.status === "active" ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{asset.status}</span></div><div className="grid gap-7 lg:grid-cols-[.85fr_1.15fr]"><section className="admin-card overflow-hidden"><div className="flex aspect-square items-center justify-center bg-slate-100">{asset.detected_mime_type.startsWith("image/") ? <img src={`/api/bff/media/${asset.id}/content`} alt={altText || "Pratinjau media"} className="h-full w-full object-contain" /> : <AdminIcon name="file" className="h-16 w-16 text-slate-300" />}</div><div className="space-y-2 p-5 text-xs text-slate-500"><p className="truncate font-bold text-slate-800">{asset.original_filename}</p><p>{asset.detected_mime_type}</p><p>{new Intl.NumberFormat("id-ID").format(asset.size_bytes)} byte</p></div></section><form onSubmit={save} className="admin-form-card"><div className="admin-form-header"><h2 className="font-black text-slate-900">Metadata media</h2><p className="mt-1 text-xs text-slate-500">Judul, teks alternatif, dan caption.</p></div><div className="admin-form-body">{error && <div className="admin-alert-error" role="alert">{error}</div>}<div><label htmlFor="media-title" className="admin-label">Judul</label><input id="media-title" value={title} onChange={(event) => setTitle(event.target.value)} className="admin-input" /></div><div><label htmlFor="media-alt" className="admin-label">Teks alternatif</label><textarea id="media-alt" rows={3} value={altText} onChange={(event) => setAltText(event.target.value)} className="admin-input" aria-describedby="media-alt-help" /><p id="media-alt-help" className="mt-2 text-xs text-slate-500">Jelaskan informasi visual penting bagi pengguna pembaca layar.</p></div><div><label htmlFor="media-caption" className="admin-label">Caption</label><textarea id="media-caption" rows={3} value={caption} onChange={(event) => setCaption(event.target.value)} className="admin-input" /></div></div><div className="admin-form-footer"><button type="button" onClick={archive} disabled={saving || asset.status !== "active"} className="admin-button-secondary !text-rose-700">Arsipkan</button><button type="submit" disabled={saving} className="admin-button">{saving ? "Menyimpan…" : "Simpan metadata"}</button></div></form></div></div>;
}
