"use client";

import { useState } from "react";
import MediaPicker from "@/components/media/MediaPicker";
import type { MediaSelection } from "@/components/media/types";
import { defaultPlatformConfiguration, sectionLabels, type PlatformConfiguration, type PlatformConfigurationState, type PlatformNavigationItem } from "@/lib/platform-configuration";

type Props = { initialState: PlatformConfigurationState };

async function requestJSON<T>(path: string, method: string, body?: unknown): Promise<T> {
  const response = await fetch(`/api/bff/platform-configuration/${path}`, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined, cache: "no-store" });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.detail || payload.title || "Operasi konfigurasi gagal");
  return payload as T;
}

const emptyLink = (): PlatformNavigationItem => ({ label: "", description: "", href: "/", visible: true });

export function PlatformConfigurationEditor({ initialState }: Props) {
  const [state, setState] = useState(initialState);
  const [config, setConfig] = useState<PlatformConfiguration>(() => structuredClone(initialState.draft?.config || initialState.published?.config || defaultPlatformConfiguration));
  const [preview, setPreview] = useState<PlatformConfiguration | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const run = async (operation: () => Promise<void>) => { setBusy(true); setError(""); setMessage(""); try { await operation(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Operasi gagal"); } finally { setBusy(false); } };
  const save = () => run(async () => {
    const revision = await requestJSON<{ version: number; config: PlatformConfiguration }>("draft", "PUT", { expected_version: state.head_version, config });
    setState((value) => ({ ...value, head_version: revision.version, draft: { ...revision, id: "", status: "draft", created_at: new Date().toISOString() }, versions: [{ ...revision, id: "", status: "draft", created_at: new Date().toISOString() }, ...value.versions] }));
    setMessage(`Draf versi ${revision.version} tersimpan.`);
  });
  const showPreview = () => run(async () => { const snapshot = await requestJSON<{ config: PlatformConfiguration }>("preview", "GET"); setPreview(snapshot.config); setMessage("Pratinjau privat dimuat dari draf tersimpan."); });
  const publish = () => run(async () => {
    if (!state.draft) throw new Error("Simpan draf sebelum menerbitkan.");
    const revision = await requestJSON<{ version: number; config: PlatformConfiguration }>("publish", "POST", { version: state.draft.version });
    setState((value) => ({ ...value, draft: undefined, published: { ...revision, id: value.draft?.id || "", status: "published", created_at: value.draft?.created_at || new Date().toISOString() }, versions: value.versions.map((item) => item.version === revision.version ? { ...item, status: "published" } : item.status === "published" ? { ...item, status: "superseded" } : item) }));
    setMessage(`Versi ${revision.version} diterbitkan secara atomik.`);
  });
  const rollback = (sourceVersion: number) => run(async () => {
    const revision = await requestJSON<{ version: number; config: PlatformConfiguration }>("rollback", "POST", { source_version: sourceVersion, expected_version: state.head_version });
    setConfig(revision.config); setPreview(null);
    setState((value) => ({ ...value, head_version: revision.version, draft: undefined, published: { ...revision, id: "", status: "published", created_at: new Date().toISOString(), based_on_version: sourceVersion }, versions: [{ ...revision, id: "", status: "published", created_at: new Date().toISOString(), based_on_version: sourceVersion }, ...value.versions.map((item) => ({ ...item, status: item.status === "published" ? "superseded" : item.status }))] }));
    setMessage(`Rollback membuat versi baru ${revision.version}.`);
  });

  const updateLink = (collection: "navigation" | "footer", index: number, patch: Partial<PlatformNavigationItem>) => setConfig((value) => {
    const links = collection === "navigation" ? [...value.navigation] : [...value.footer.links]; links[index] = { ...links[index], ...patch };
    return collection === "navigation" ? { ...value, navigation: links } : { ...value, footer: { ...value.footer, links } };
  });
  const setMedia = (field: "logo" | "banner" | "social", selection: MediaSelection) => setConfig((value) => field === "logo" ? { ...value, identity: { ...value.identity, logo_media_id: selection.id } } : field === "banner" ? { ...value, banner: { ...value.banner, media_id: selection.id } } : { ...value, seo: { ...value.seo, social_media_id: selection.id } });

  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]">
    <div className="grid gap-6">
      {error && <div className="admin-alert-error" role="alert">{error}</div>}
      {message && <div className="rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm font-bold text-sky-900" role="status">{message}</div>}

      <section className="admin-form-card"><div className="admin-form-header"><div><p className="admin-kicker">Identitas tetap</p><h2 className="font-black">Presentasi Teman Belajar</h2></div><span className="admin-status bg-slate-100 text-slate-700">Nama produk terkunci</span></div><div className="admin-form-body grid gap-5 md:grid-cols-2"><label className="admin-label">Tagline<input className="admin-input mt-2" maxLength={120} value={config.identity.tagline} onChange={(event) => setConfig((value) => ({ ...value, identity: { ...value.identity, tagline: event.target.value } }))} /></label><div><p className="admin-label">Logo dari Pustaka Media</p><div className="mt-2 flex flex-wrap items-center gap-3"><MediaPicker imageOnly buttonLabel="Pilih logo" onSelect={(selection) => setMedia("logo", selection)} />{config.identity.logo_media_id && <><code className="text-xs text-slate-500">{config.identity.logo_media_id}</code><button className="admin-button-secondary" type="button" onClick={() => setConfig((value) => ({ ...value, identity: { ...value.identity, logo_media_id: undefined } }))}>Hapus</button></>}</div></div></div></section>

      <section className="admin-form-card"><div className="admin-form-header"><div><p className="admin-kicker">Beranda</p><h2 className="font-black">Urutan dan visibilitas section</h2></div></div><div className="admin-form-body grid gap-3 sm:grid-cols-2">{config.homepage.sections.map((section, index) => <div key={section.key} className="grid grid-cols-[1fr_76px] items-center gap-3 rounded-xl border p-3"><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={section.visible} onChange={(event) => setConfig((value) => ({ ...value, homepage: { sections: value.homepage.sections.map((item, itemIndex) => itemIndex === index ? { ...item, visible: event.target.checked } : item) } }))} />{sectionLabels[section.key] || section.key}</label><label className="sr-only" htmlFor={`section-order-${section.key}`}>Urutan {section.key}</label><input id={`section-order-${section.key}`} className="admin-input" type="number" min={1} max={9} value={section.order} onChange={(event) => setConfig((value) => ({ ...value, homepage: { sections: value.homepage.sections.map((item, itemIndex) => itemIndex === index ? { ...item, order: Number(event.target.value) } : item) } }))} /></div>)}</div></section>

      <LinkEditor title="Navigasi publik" links={config.navigation} onChange={(index, patch) => updateLink("navigation", index, patch)} onAdd={() => setConfig((value) => ({ ...value, navigation: [...value.navigation, emptyLink()] }))} onRemove={(index) => setConfig((value) => ({ ...value, navigation: value.navigation.filter((_, itemIndex) => itemIndex !== index) }))} />

      <section className="admin-form-card"><div className="admin-form-header"><div><p className="admin-kicker">Banner</p><h2 className="font-black">Pengumuman presentasi</h2></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={config.banner.enabled} onChange={(event) => setConfig((value) => ({ ...value, banner: { ...value.banner, enabled: event.target.checked } }))} /> Aktif</label></div><div className="admin-form-body grid gap-4"><label className="admin-label">Judul<input className="admin-input mt-2" maxLength={120} value={config.banner.title} onChange={(event) => setConfig((value) => ({ ...value, banner: { ...value.banner, title: event.target.value } }))} /></label><label className="admin-label">Isi<textarea className="admin-input mt-2 min-h-24" maxLength={400} value={config.banner.body} onChange={(event) => setConfig((value) => ({ ...value, banner: { ...value.banner, body: event.target.value } }))} /></label><label className="admin-label">Tautan aman<input className="admin-input mt-2" value={config.banner.href || ""} onChange={(event) => setConfig((value) => ({ ...value, banner: { ...value.banner, href: event.target.value } }))} /></label><div className="flex flex-wrap items-center gap-3"><MediaPicker imageOnly buttonLabel="Pilih gambar banner" onSelect={(selection) => setMedia("banner", selection)} />{config.banner.media_id && <code className="text-xs text-slate-500">{config.banner.media_id}</code>}</div></div></section>

      <section className="admin-form-card"><div className="admin-form-header"><h2 className="font-black">Footer, bantuan, dan SEO</h2></div><div className="admin-form-body grid gap-4"><label className="admin-label">Ringkasan footer<textarea className="admin-input mt-2 min-h-24" maxLength={400} value={config.footer.summary} onChange={(event) => setConfig((value) => ({ ...value, footer: { ...value.footer, summary: event.target.value } }))} /></label><div className="grid gap-4 md:grid-cols-2"><label className="admin-label">Label bantuan<input className="admin-input mt-2" value={config.contact.help_label} onChange={(event) => setConfig((value) => ({ ...value, contact: { ...value.contact, help_label: event.target.value } }))} /></label><label className="admin-label">Tautan bantuan<input className="admin-input mt-2" value={config.contact.help_href} onChange={(event) => setConfig((value) => ({ ...value, contact: { ...value.contact, help_href: event.target.value } }))} /></label><label className="admin-label">Email kontak<input className="admin-input mt-2" type="email" value={config.contact.email || ""} onChange={(event) => setConfig((value) => ({ ...value, contact: { ...value.contact, email: event.target.value } }))} /></label><label className="admin-label">Judul SEO bawaan<input className="admin-input mt-2" maxLength={70} value={config.seo.default_title} onChange={(event) => setConfig((value) => ({ ...value, seo: { ...value.seo, default_title: event.target.value } }))} /></label></div><label className="admin-label">Deskripsi SEO bawaan<textarea className="admin-input mt-2 min-h-20" maxLength={180} value={config.seo.default_description} onChange={(event) => setConfig((value) => ({ ...value, seo: { ...value.seo, default_description: event.target.value } }))} /></label><div className="flex flex-wrap items-center gap-3"><MediaPicker imageOnly buttonLabel="Pilih gambar sosial" onSelect={(selection) => setMedia("social", selection)} />{config.seo.social_media_id && <code className="text-xs text-slate-500">{config.seo.social_media_id}</code>}</div></div></section>

      <LinkEditor title="Tautan footer" links={config.footer.links} onChange={(index, patch) => updateLink("footer", index, patch)} onAdd={() => setConfig((value) => ({ ...value, footer: { ...value.footer, links: [...value.footer.links, emptyLink()] } }))} onRemove={(index) => setConfig((value) => ({ ...value, footer: { ...value.footer, links: value.footer.links.filter((_, itemIndex) => itemIndex !== index) } }))} />

      <section className="admin-form-card"><div className="admin-form-header"><div><p className="admin-kicker">Presentasi fitur aktif</p><h2 className="font-black">Label dan visibilitas</h2><p className="mt-1 text-xs text-slate-500">Tidak mengubah route atau authorization.</p></div></div><div className="admin-form-body grid gap-3 md:grid-cols-2">{config.features.map((feature, index) => <div key={feature.key} className="rounded-xl border p-3"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={feature.visible} onChange={(event) => setConfig((value) => ({ ...value, features: value.features.map((item, itemIndex) => itemIndex === index ? { ...item, visible: event.target.checked } : item) }))} />{feature.key}</label><input className="admin-input mt-2" maxLength={80} value={feature.label} onChange={(event) => setConfig((value) => ({ ...value, features: value.features.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item) }))} /></div>)}</div></section>
    </div>

    <aside className="grid content-start gap-6 xl:sticky xl:top-6 xl:self-start"><section className="admin-form-card"><div className="admin-form-header"><div><p className="admin-kicker">Versi {state.head_version}</p><h2 className="font-black">Publikasi</h2></div></div><div className="admin-form-body grid gap-3"><button type="button" disabled={busy} className="admin-button" onClick={save}>Simpan draf</button><button type="button" disabled={busy || !state.draft} className="admin-button-secondary" onClick={showPreview}>Pratinjau privat</button><button type="button" disabled={busy || !state.draft} className="admin-button" onClick={publish}>Terbitkan draf</button><p className="text-xs leading-5 text-slate-500">Optimistic versioning mencegah perubahan tertimpa. Publish dan rollback bersifat atomik.</p></div></section>
      {preview && <section className="overflow-hidden rounded-2xl border bg-white shadow-sm" aria-label="Pratinjau privat"><div className="bg-sky-700 px-5 py-4 text-white"><p className="text-xs font-black uppercase tracking-wider">Pratinjau Admin</p><p className="mt-1 text-xl font-black">Teman Belajar</p><p className="text-sm text-sky-100">{preview.identity.tagline}</p></div>{preview.banner.enabled && <div className="border-b bg-sky-50 p-4"><p className="font-black text-slate-900">{preview.banner.title}</p><p className="mt-1 text-sm text-slate-600">{preview.banner.body}</p></div>}<div className="p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Navigasi</p><div className="mt-3 flex flex-wrap gap-2">{preview.navigation.filter((item) => item.visible).map((item) => <span key={`${item.label}-${item.href}`} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{item.label}</span>)}</div></div></section>}
      <section className="admin-form-card"><div className="admin-form-header"><h2 className="font-black">Riwayat immutable</h2></div><div className="admin-form-body grid gap-3">{state.versions.length ? state.versions.map((revision) => <div key={revision.version} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><p className="font-black">Versi {revision.version}</p><span className="admin-status bg-slate-100 text-slate-700">{revision.status}</span></div><p className="mt-1 text-xs text-slate-500">{new Date(revision.created_at).toLocaleString("id-ID")}</p>{revision.status === "superseded" && <button type="button" disabled={busy} className="admin-button-secondary mt-3 w-full" onClick={() => rollback(revision.version)}>Rollback sebagai versi baru</button>}</div>) : <p className="text-sm text-slate-500">Belum ada versi tersimpan.</p>}</div></section>
    </aside>
  </div>;
}

function LinkEditor({ title, links, onChange, onAdd, onRemove }: { title: string; links: PlatformNavigationItem[]; onChange: (index: number, patch: Partial<PlatformNavigationItem>) => void; onAdd: () => void; onRemove: (index: number) => void }) {
  return <section className="admin-form-card"><div className="admin-form-header"><h2 className="font-black">{title}</h2><button className="admin-button-secondary" type="button" onClick={onAdd}>Tambah tautan</button></div><div className="admin-form-body grid gap-4">{links.map((link, index) => <fieldset key={index} className="grid gap-3 rounded-xl border p-4 md:grid-cols-2"><legend className="px-2 text-xs font-black uppercase tracking-wider text-slate-500">Tautan {index + 1}</legend><label className="admin-label">Label<input className="admin-input mt-2" value={link.label} maxLength={80} onChange={(event) => onChange(index, { label: event.target.value })} /></label><label className="admin-label">Path internal / HTTPS allowlist<input className="admin-input mt-2" value={link.href} onChange={(event) => onChange(index, { href: event.target.value })} /></label><label className="admin-label md:col-span-2">Deskripsi<input className="admin-input mt-2" value={link.description || ""} maxLength={180} onChange={(event) => onChange(index, { description: event.target.value })} /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={link.visible} onChange={(event) => onChange(index, { visible: event.target.checked })} /> Tampilkan</label><button type="button" className="admin-button-secondary justify-self-start md:justify-self-end" onClick={() => onRemove(index)}>Hapus</button></fieldset>)}</div></section>;
}
