import type { Metadata } from "next";
/* eslint-disable @next/next/no-img-element -- public media route is access-controlled and not compatible with the image optimizer */
import Link from "next/link";

import { EmptyState, ErrorState, PageHero } from "@/components/public-content";
import { listMicrolearning, type MicrolearningFormat } from "@/lib/microlearning";

export const metadata: Metadata = { title: "Pembelajaran Singkat", description: "Materi editorial terkurasi selama 3–15 menit di Teman Belajar.", alternates: { canonical: "/microlearning" } };
const labels: Record<MicrolearningFormat, string> = { article: "Artikel", video: "Video", quick: "Quick learning" };
function href(q: string, format: string, page: number) { const p = new URLSearchParams(); if (q) p.set("q", q); if (format) p.set("format", format); if (page > 1) p.set("page", String(page)); return `/microlearning${p.size ? `?${p}` : ""}`; }

export default async function MicrolearningPage({ searchParams }: { searchParams: Promise<{ q?: string; format?: string; page?: string }> }) {
  const raw = await searchParams; const query = (raw.q || "").trim().slice(0, 100); const format = ["article", "video", "quick"].includes(raw.format || "") ? raw.format || "" : ""; const page = Math.max(1, Number.parseInt(raw.page || "1", 10) || 1); const result = await listMicrolearning(query, format, page);
  return <div><PageHero eyebrow="Pembelajaran Singkat" title="Wawasan praktis dalam 3–15 menit" description="Pilih artikel, video, atau quick learning editorial. Aktivitas ini milik Portal dan tidak menggantikan course, completion, atau penilaian Moodle." />
    <section className="portal-container py-10 sm:py-14">
      <form role="search" action="/microlearning" className="portal-card grid gap-4 p-5 sm:grid-cols-[minmax(0,1fr)_12rem_auto] sm:items-end"><div><label htmlFor="microlearning-search" className="portal-label">Cari materi</label><input id="microlearning-search" name="q" type="search" maxLength={100} defaultValue={query} className="portal-search-input mt-2 w-full" placeholder="Topik atau judul" /></div><div><label htmlFor="microlearning-format" className="portal-label">Format</label><select id="microlearning-format" name="format" defaultValue={format} className="portal-control mt-2 w-full"><option value="">Semua format</option><option value="quick">Quick learning</option><option value="article">Artikel</option><option value="video">Video</option></select></div><button className="portal-button-primary">Terapkan</button></form>
      {result.error ? <div className="mt-8"><ErrorState title="Pembelajaran Singkat belum dapat dimuat" /></div> : result.data.length === 0 ? <div className="mt-8"><EmptyState title={query || format ? "Materi tidak ditemukan" : "Belum ada materi terbit"} description="Materi yang telah ditinjau dan diterbitkan akan tampil di sini." /></div> : <><div className="mb-6 mt-10 flex items-end justify-between"><div><p className="portal-eyebrow">Katalog editorial</p><h2 className="mt-2 text-2xl font-black text-slate-900">Materi siap dipelajari</h2></div><p className="text-sm font-semibold text-slate-500">{result.pagination.total} materi</p></div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{result.data.map((item) => <article key={item.id} className="portal-card portal-course-card overflow-hidden"><div className="aspect-[16/9] bg-gradient-to-br from-teal-700 to-sky-700">{item.featured_media_id ? <img src={`/media/${item.featured_media_id}`} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-4xl font-black text-white/80">{item.duration_minutes}</div>}</div><div className="flex flex-1 flex-col p-6"><div className="flex gap-2"><span className="portal-badge">{labels[item.format]}</span><span className="portal-badge">{item.duration_minutes} menit</span></div><h3 className="mt-5 text-xl font-black text-slate-900"><Link href={`/microlearning/${item.slug}`} className="hover:text-teal-700">{item.title}</Link></h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{item.summary}</p><Link href={`/microlearning/${item.slug}`} className="mt-auto border-t border-slate-100 pt-5 font-extrabold text-teal-700">Mulai materi →</Link></div></article>)}</div>{result.pagination.total_pages > 1 ? <nav className="mt-10 flex items-center justify-between" aria-label="Paginasi materi"><Link aria-disabled={page <= 1} tabIndex={page <= 1 ? -1 : undefined} href={href(query, format, Math.max(1, page - 1))} className={`portal-button-secondary ${page <= 1 ? "pointer-events-none opacity-40" : ""}`}>← Sebelumnya</Link><span className="text-sm font-bold text-slate-500">Halaman {page} dari {result.pagination.total_pages}</span><Link aria-disabled={page >= result.pagination.total_pages} tabIndex={page >= result.pagination.total_pages ? -1 : undefined} href={href(query, format, Math.min(result.pagination.total_pages, page + 1))} className={`portal-button-secondary ${page >= result.pagination.total_pages ? "pointer-events-none opacity-40" : ""}`}>Berikutnya →</Link></nav> : null}</>}
    </section></div>;
}
