"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

import { AdminIcon } from "@/components/admin-icon";
import { createTrainingProgramAction, getTrainingWorkspaceAction, transitionTrainingProgramAction, updateTrainingProgramAction, type TrainingCohortInput, type TrainingCourseInput, type TrainingCourseOption, type TrainingProgram, type TrainingProgramInput } from "@/app/actions/training-programs";

type Draft = Omit<TrainingProgramInput, "expected_version">;
const emptyDraft: Draft = { slug: "", title: "", summary: "", description: "", audience: "", eligibility_text: "", courses: [], cohorts: [] };
const labels: Record<string,string> = { draft: "Draf", in_review: "Peninjauan", approved: "Disetujui", published: "Terbit", archived: "Diarsipkan" };
const slugify = (value:string) => value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0,160);
const toInputDate = (value?: string | null) => value ? new Date(value).toISOString().slice(0,16) : "";
const fromInputDate = (value: string) => value ? new Date(value).toISOString() : null;

function draftFrom(item: TrainingProgram): Draft {
  return { slug: item.slug, title: item.title, summary: item.summary, description: item.description, audience: item.audience || "", eligibility_text: item.eligibility_text || "", courses: item.courses.map(course => ({ moodle_course_id: course.moodle_course_id, required: course.required })), cohorts: item.cohorts.map(cohort => ({ label: cohort.label, starts_at: cohort.starts_at || null, ends_at: cohort.ends_at || null, enrollment_opens_at: cohort.enrollment_opens_at || null, enrollment_closes_at: cohort.enrollment_closes_at || null, status: cohort.status })) };
}

export default function TrainingProgramsAdminPage() {
  const [programs,setPrograms]=useState<TrainingProgram[]>([]); const [options,setOptions]=useState<TrainingCourseOption[]>([]); const [roles,setRoles]=useState<string[]>([]); const [selected,setSelected]=useState<TrainingProgram|null>(null); const [draft,setDraft]=useState<Draft>(emptyDraft); const [creating,setCreating]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [query,setQuery]=useState(""); const [status,setStatus]=useState("all");
  const canWrite=roles.some(role=>["Portal Administrator","Content Editor"].includes(role)); const canReview=roles.some(role=>["Portal Administrator","Reviewer"].includes(role));
  const load=useCallback(async()=>{const result=await getTrainingWorkspaceAction({q:query,status});setLoading(false);if(!result.success){setError(result.error);setPrograms([]);setOptions(result.courses);setRoles(result.roles);return;}setPrograms(result.programs);setOptions(result.courses);setRoles(result.roles);setError("");},[query,status]);
  useEffect(()=>{let active=true;void getTrainingWorkspaceAction({q:query,status}).then(result=>{if(!active)return;setLoading(false);if(!result.success){setError(result.error);setPrograms([]);setOptions(result.courses);setRoles(result.roles);return;}setPrograms(result.programs);setOptions(result.courses);setRoles(result.roles);setError("");});return()=>{active=false}},[query,status]);
  const choose=(item:TrainingProgram)=>{setSelected(item);setDraft(draftFrom(item));setCreating(false);setError("");setNotice("");};
  const startCreate=()=>{setSelected(null);setDraft(emptyDraft);setCreating(true);setError("");setNotice("");};
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}));
  const editable=canWrite&&(!selected||selected.status==="draft");
  const selectedCourseIds=useMemo(()=>new Set(draft.courses.map(item=>item.moodle_course_id)),[draft.courses]);
  const addCourse=(course:TrainingCourseOption)=>set("courses",[...draft.courses,{moodle_course_id:course.id,required:true}]);
  const moveCourse=(index:number,direction:-1|1)=>{const next=[...draft.courses];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];set("courses",next)};
  const updateCohort=(index:number,key:keyof TrainingCohortInput,value:string|null)=>set("cohorts",draft.cohorts.map((item,i)=>i===index?{...item,[key]:value}:item));
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError("");const input:TrainingProgramInput={...draft,expected_version:selected?.version};const result=selected?await updateTrainingProgramAction(selected.id,input):await createTrainingProgramAction(input);setBusy(false);if(!result.success){setError(result.error);return;}setNotice(selected?"Program berhasil diperbarui.":"Draf program berhasil dibuat.");setSelected(result.data);setDraft(draftFrom(result.data));setCreating(false);await load();};
  const transition=async(next:TrainingProgram["status"])=>{if(!selected)return;setBusy(true);const result=await transitionTrainingProgramAction(selected.id,next);setBusy(false);if(!result.success){setError(result.error);return;}setSelected(result.data);setDraft(draftFrom(result.data));setNotice(`Program dipindahkan ke ${labels[next]}.`);await load();};
  const actions: Array<{status:TrainingProgram["status"];label:string}>=[]; if(selected?.status==="draft"&&canWrite)actions.push({status:"in_review",label:"Ajukan peninjauan"});if(selected?.status==="in_review"&&canReview)actions.push({status:"draft",label:"Kembalikan ke draf"},{status:"approved",label:"Setujui"});if(selected?.status==="approved"&&canReview)actions.push({status:"draft",label:"Kembalikan ke draf"},{status:"published",label:"Terbitkan"});if(selected?.status==="published"&&(canWrite||canReview))actions.push({status:"archived",label:"Arsipkan"});

  return <div className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">TASK-013 · Moodle composition</p><h1 className="admin-page-title">Program Pelatihan</h1><p className="admin-page-copy">Susun program, cohort, dan urutan course. Enrolment serta completion tetap dikelola Moodle.</p></div>{canWrite?<button type="button" className="admin-button" onClick={startCreate}><AdminIcon name="file" className="h-4 w-4"/>Program baru</button>:null}</header>
    {error?<div role="alert" className="mb-5 rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm font-bold text-rose-800">{error}</div>:null}{notice?<div role="status" className="mb-5 rounded-xl border border-sky-300 bg-sky-50 p-4 text-sm font-bold text-sky-900">{notice}</div>:null}
    <div className="grid gap-6 xl:grid-cols-[23rem_minmax(0,1fr)]"><aside className="admin-card self-start"><div className="admin-card-header"><h2 className="font-black">Daftar program</h2></div><div className="admin-card-body"><form onSubmit={event=>{event.preventDefault();void load()}} className="grid gap-3"><label htmlFor="program-search" className="admin-label">Cari program</label><input id="program-search" className="admin-input" value={query} maxLength={100} onChange={event=>setQuery(event.target.value)} placeholder="Judul atau sasaran"/><label htmlFor="program-status" className="admin-label">Status</label><select id="program-status" className="admin-input" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Semua status</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></form><div className="mt-5 grid gap-2">{loading?<p role="status" className="text-sm text-slate-500">Memuat program…</p>:programs.length===0?<p className="admin-empty">Belum ada program pada filter ini.</p>:programs.map(item=><button type="button" key={item.id} onClick={()=>choose(item)} className={`admin-list-item text-left ${selected?.id===item.id?"is-active":""}`}><span><strong className="block text-sm">{item.title}</strong><span className="mt-1 block text-xs opacity-70">{item.courses.length} course · {item.cohorts.length} cohort</span></span><span className="admin-status admin-status-neutral">{labels[item.status]}</span></button>)}</div></div></aside>
      <main>{!selected&&!creating?<div className="admin-empty rounded-2xl border"><span className="admin-stat-icon mx-auto"><AdminIcon name="knowledge" className="h-5 w-5"/></span><h2 className="mt-4 text-xl font-black">Pilih program untuk melihat komposisi</h2><p className="mt-2">Atau buat draf program baru dari katalog course Moodle.</p></div>:<form onSubmit={submit} className="admin-form-card"><div className="admin-form-header"><div><p className="admin-kicker">{selected?"Detail program":"Program baru"}</p><h2 className="text-xl font-black">{selected?.title||"Susun pengalaman pelatihan"}</h2><p className="mt-1 text-xs text-slate-500">Publikasi memvalidasi ulang setiap course terhadap Moodle.</p></div>{selected?<span className="admin-status admin-status-neutral">{labels[selected.status]}</span>:null}</div><fieldset disabled={!editable||busy} className="admin-form-body"><div className="grid gap-5 md:grid-cols-2"><div><label htmlFor="program-title" className="admin-label">Judul *</label><input id="program-title" required minLength={3} maxLength={200} className="admin-input" value={draft.title} onChange={event=>{set("title",event.target.value);if(!selected)set("slug",slugify(event.target.value))}}/></div><div><label htmlFor="program-slug" className="admin-label">Slug *</label><input id="program-slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={160} className="admin-input" value={draft.slug} onChange={event=>set("slug",event.target.value)}/></div></div><div><label htmlFor="program-summary" className="admin-label">Ringkasan *</label><textarea id="program-summary" required minLength={10} maxLength={500} rows={3} className="admin-input" value={draft.summary} onChange={event=>set("summary",event.target.value)}/></div><div><label htmlFor="program-description" className="admin-label">Deskripsi *</label><textarea id="program-description" required minLength={20} maxLength={20000} rows={7} className="admin-input" value={draft.description} onChange={event=>set("description",event.target.value)}/></div><div className="grid gap-5 md:grid-cols-2"><div><label htmlFor="program-audience" className="admin-label">Sasaran peserta</label><textarea id="program-audience" maxLength={500} rows={3} className="admin-input" value={draft.audience} onChange={event=>set("audience",event.target.value)}/></div><div><label htmlFor="program-eligibility" className="admin-label">Panduan eligibility</label><textarea id="program-eligibility" maxLength={1000} rows={3} className="admin-input" value={draft.eligibility_text} onChange={event=>set("eligibility_text",event.target.value)}/><p className="mt-2 text-xs text-slate-500">Copy ini tidak mengonfirmasi akses; CTA publik memakai state API Moodle.</p></div></div>
        <section><div className="mb-3 flex items-end justify-between"><div><h3 className="font-black">Komposisi course *</h3><p className="text-xs text-slate-500">Urutan ini menjadi urutan belajar pada Portal.</p></div><span className="admin-status admin-status-neutral">{draft.courses.length}/50</span></div><div className="grid gap-3">{draft.courses.map((course,index)=>{const option=options.find(item=>item.id===course.moodle_course_id);return <div key={course.moodle_course_id} className="admin-taxonomy-row"><div><p className="font-black">{index+1}. {option?.full_name||`Course #${course.moodle_course_id}`}</p><p className="mt-1 text-xs text-slate-500">Moodle ID {course.moodle_course_id}</p></div><div className="flex flex-wrap items-center gap-2"><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={course.required} onChange={event=>set("courses",draft.courses.map((item,i)=>i===index?{...item,required:event.target.checked}:item))}/>Wajib</label><button type="button" className="admin-button-secondary" aria-label={`Naikkan ${option?.full_name||course.moodle_course_id}`} onClick={()=>moveCourse(index,-1)}>↑</button><button type="button" className="admin-button-secondary" aria-label={`Turunkan ${option?.full_name||course.moodle_course_id}`} onClick={()=>moveCourse(index,1)}>↓</button><button type="button" className="admin-button-secondary" onClick={()=>set("courses",draft.courses.filter((_,i)=>i!==index))}>Hapus</button></div></div>})}</div><label htmlFor="course-picker" className="admin-label mt-4">Tambah dari katalog Moodle</label><select id="course-picker" className="admin-input" value="" onChange={event=>{const option=options.find(item=>item.id===Number(event.target.value));if(option)addCourse(option)}}><option value="">Pilih course…</option>{options.filter(item=>!selectedCourseIds.has(item.id)).map(option=><option key={option.id} value={option.id}>{option.full_name} ({option.short_name})</option>)}</select></section>
        <section><div className="mb-3 flex items-end justify-between"><div><h3 className="font-black">Cohort dan jadwal</h3><p className="text-xs text-slate-500">Waktu ditampilkan pada Portal dengan zona Asia/Jakarta.</p></div><button type="button" className="admin-button-secondary" onClick={()=>set("cohorts",[...draft.cohorts,{label:"",starts_at:null,ends_at:null,enrollment_opens_at:null,enrollment_closes_at:null,status:"scheduled"}])}>Tambah cohort</button></div><div className="grid gap-4">{draft.cohorts.map((cohort,index)=><fieldset key={index} className="admin-disclosure"><legend className="font-black">Cohort {index+1}</legend><div className="mt-3 grid gap-4 md:grid-cols-2"><div><label htmlFor={`cohort-label-${index}`} className="admin-label">Label *</label><input id={`cohort-label-${index}`} required maxLength={160} className="admin-input" value={cohort.label} onChange={event=>updateCohort(index,"label",event.target.value)}/></div><div><label htmlFor={`cohort-status-${index}`} className="admin-label">Status</label><select id={`cohort-status-${index}`} className="admin-input" value={cohort.status} onChange={event=>updateCohort(index,"status",event.target.value)}><option value="scheduled">Terjadwal</option><option value="completed">Selesai</option><option value="cancelled">Dibatalkan</option></select></div>{([['starts_at','Mulai'],['ends_at','Selesai'],['enrollment_opens_at','Pendaftaran dibuka'],['enrollment_closes_at','Pendaftaran ditutup']] as const).map(([key,label])=><div key={key}><label htmlFor={`${key}-${index}`} className="admin-label">{label}</label><input id={`${key}-${index}`} type="datetime-local" className="admin-input" value={toInputDate(cohort[key])} onChange={event=>updateCohort(index,key,fromInputDate(event.target.value))}/></div>)}</div><button type="button" className="admin-button-secondary mt-4" onClick={()=>set("cohorts",draft.cohorts.filter((_,i)=>i!==index))}>Hapus cohort</button></fieldset>)}</div></section></fieldset><div className="admin-form-footer"><button type="button" className="admin-button-secondary" onClick={()=>{setSelected(null);setCreating(false)}}>Tutup</button>{editable?<button type="submit" className="admin-button" disabled={busy||draft.courses.length===0}>{busy?"Menyimpan…":selected?"Simpan perubahan":"Simpan draf"}</button>:null}</div></form>}
        {selected&&actions.length?<section className="admin-form-card mt-5"><div className="admin-form-header"><div><h2 className="font-black">Alur publikasi</h2><p className="mt-1 text-xs text-slate-500">Reviewer mengubah status; penulisan tetap terpisah.</p></div></div><div className="admin-form-body flex flex-wrap gap-3">{actions.map(action=><button key={action.status} type="button" disabled={busy} className={action.status==="published"?"admin-button":"admin-button-secondary"} onClick={()=>void transition(action.status)}>{action.label}</button>)}</div></section>:null}</main></div>
  </div>;
}
